### ISSUE TITLE
Add bipartite graph to show tower/region cover

### ISSUE THREAD

**Issue by cmaes** [EmilienDupont/telecom#5]
In the description of this example, I mention a bipartite graph G(T,R,E) between towers T and regions R, where we place an edge (i,j) in E if region j is covered by tower i.  It would be good to do a simple visualization of this graph near this explanation in the text. It only needs to have a few towers and a few regions. Hovering over a tower should highlight all the regions (nodes) that the tower covers. Hovering over a region, should highlight all towers that cover that region.

**Comment by EmilienDupont** [comment]
Done!
